### ISSUE TITLE
Is there a full API documentation?

### ISSUE THREAD

**Issue by xetra11** [kittykatattack/hexi#19]
I'm looking for a full API documentation. Only using the Tutorials isn't helpful when It try to look for a specific functionality

**Comment by Edisoni** [comment]
+1

**Comment by icarito** [comment]
@Edisoni @xetra11 I guess for the most part you are looking for this:
http://pixijs.github.io/docs/PIXI.Sprite.html :-D

Let's add it to the README!

**Comment by xetra11** [comment]
@icarito 
I was more talking about the higher level API of Hexi not PIXIs doc. Or did I misunderstand you?

**Comment by icarito** [comment]
Yes you are right, API docs for hexi itself would nice to have. There is some valuable info in the comments for https://github.com/kittykatattack/hexi/blob/master/src/core.js with pointers to each of the components where other examples are to be found.

**Comment by kittykatattack** [comment]
Hi Everyone,

No, there aren't any API docs, and won't ever be.
100% of Hexi features and functionality is covered in the examples and tutorials folder.
