### ISSUE TITLE
Ability to put canvas into any <div>

### ISSUE THREAD

**Issue by icarito** [kittykatattack/hexi#20]
I tried reparenting inside a container and then scaling became an issue. I'd like to _scaleToElement_ if you know what I mean ;-) I'm not a javascript expert...

**Comment by icarito** [comment]
Incidentally, the reason I need this is because *scaleToWindow* doesn't work well for me in a wide, scaled viewport (320, 120)

**Comment by icarito** [comment]
![image](https://cloud.githubusercontent.com/assets/199755/19616253/b34aef8c-97d3-11e6-88e4-0c597d6e84c6.png)

**Comment by icarito** [comment]
For the specific issue in Chromium I was able to work around it with:
```
    body {
        overflow:hidden;
    }
```

**Comment by kittykatattack** [comment]
Thanks for reporting this!
