### ISSUE TITLE
makeTiledWorld import .tsx tileset file

### ISSUE THREAD

**Issue by thomasverleye** [kittykatattack/hexi#48]
Hello,

First of, awesome project, I'm taking really big shortcuts for a project I'm working on with this codebase!
I'm wondering if it's possible to read a .tsx tileset file instead of having to import the whole tileset into the tiled .json export. I could use this because on the designteam I'm working with is using 1 general .tsx tileset file to create their levels.

Kind regards,

Thomas Verleye

**Comment by kittykatattack** [comment]
Hi Thomas!

Glad you're enjoying Hexi!
I'm using it every day for my production work too (making educational games.)

I'm really sorry but reading `.tsx` files is not a feature.
Also, it's not on my road map for future, but if someone wants to create a plugin for it, that would be awesome!
The place to do it would be in this module:

https://github.com/kittykatattack/tileUtilities

**Comment by icarito** [comment]
While we are thinking of features, the one I miss is support for multiple tilesets. Tiled allows the use of different tiles (e.g. I might have items in one tileset and then map tiles in another tileset).

I guess Thomas meant `.tmx` files which is Tiled's native format. `.json` serves me well.

Another observation:
  - If I have a map without a "name" tile property for at least one tile, it will fail to load. This is strange and was hard to catch for me.
