### ISSUE TITLE
Tutorials not working

### ISSUE THREAD

**Issue by hiperbou** [kittykatattack/hexi#6]
Tutorial Alien Armada just crashes because the keys are not defined (g.leftArrow, etc)
Tutorial Flappy Fairy does not work on Firefox, it seems that the pointer is not working.

**Comment by artyprog** [comment]
Thanks for tis awesome library :-)

The shoot method does not seems work. I am using fIrefox.

Regards

**Comment by kittykatattack** [comment]
I'm in the process of fixing this.
For the Alien Armada tutorial, just delete the `g.` prefix from all the arrow key objects for now.
For Firefox bug - I'm investigating that. It looks like Firefox made a recent change that is not compatible with the pointer code, I'll find out what that is an fix it.
Thanks for reporting this!

**Comment by kittykatattack** [comment]
... Just letting you know that the keyboard control bug in Alien Armada is now fixed:

https://github.com/kittykatattack/hexi/blob/master/tutorials/src/alienArmada.js

**Comment by kittykatattack** [comment]
The Flappy Fairy bug in Firefox was related to a buggy fullscreen API implementation.
I've removed the module that was causing the problem, and opened a new issue to begin a discussion about creating a new fullscreen module:

https://github.com/kittykatattack/hexi/issues/14
