### ISSUE TITLE
Isometric example

### ISSUE THREAD

**Issue by lawalm** [kittykatattack/hexi#7]
How do I add a new sprite property.  I have tried add it to the addIsoProperties, error states the enemy is not define however I defined it in the switch statement.

 case 4:
            sprite = g.isoRectangle(world.cartTilewidth, world.cartTileheight, 0xFF99FF);
            //Cartesian rectangle:
           // sprite = g.rectangle(world.cartTilewidth, world.cartTileheight, 0xFF0000);

            //Define this sprite as the `enemy`
            enemy = sprite;                

Any assistance will be appreciated. 

It appears to be resolved. I created a new layer, however any tips working with isoRectangle method wll be appreciated. 

5mins later back to the same problem. case 3 and 4 are now pink even though they are on different layers.  See code below. 

   //The character  
          case 3:
            sprite = g.isoRectangle(world.cartTilewidth, world.cartTileheight, 0xFF0000);
            //Define this sprite as the `player`
            player = sprite;
          
 //the enemy      
           case 4:
            sprite = g.isoRectangle(world.cartTilewidth, world.cartTileheight, 0xFF99FF);
            //Define this sprite as the `player`
            enemy = sprite;        
Why would this be?

Thanks.

**Comment by kittykatattack** [comment]
Have you tried this?
```
player = g.isoRectangle(world.cartTilewidth, world.cartTileheight, 0xFF0000);
enemy = g.isoRectangle(world.cartTilewidth, world.cartTileheight, 0xFF99FF);
```

**Comment by lawalm** [comment]
Yes, thanks for the reply, I have resolved the issue now.  I really like your Hexi Engine, I also have the agd book which is rather good as well.
